<?php
/**
 * Created by PhpStorm.
 * User: dezer
 * Date: 12.02.18
 * Time: 1:46
 */

namespace LocalUpload;

require_once __DIR__.'/abstract/RemoteUploadAbstract.php';

class RemoteUpload extends RemoteUploadAbstract
{
    function requestData($requestParams)
    {
        parent::requestData($requestParams); // TODO: Change the autogenerated stub
    }

    function parseRequest($response)
    {
        parent::parseRequest($response); // TODO: Change the autogenerated stub
    }

}